### Class exercise: table
![](http://127.0.0.1:8888/files/images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [18]:
import numpy as np
a = np.arange(10, 30).reshape(4, 5)
yellow = a[0, 0]
cyan = a[:, 1::2]
green = a[0:3,2]
blue = a[0::2,4]
red = a[0, 1:4]

print("yellow:",yellow,"\ncyan:",cyan,"\ngreen:",green,"\nblue:",blue,"\nred:",red)

yellow: 10 
cyan: [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
green: [12 17 22] 
blue: [14 24] 
red: [11 12 13]


### Class exercise: cube
![](http://127.0.0.1:8888/files/images/cube.png)
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [25]:
a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)

print('1 task: \n',a[1,1,:],'\n---------')
print('2 task: \n',a[:,1,0],'\n---------')
print('3 task: \n',a[0,:,2],'\n---------')

1 task: 
 [12 13 14] 
---------
2 task: 
 [ 3 12 21] 
---------
3 task: 
 [2 5 8] 
---------


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6


In [54]:
data = np.arange(1,101).reshape(10,10)
print(data)
datab = data %2==0
print(data[datab])
datac = np.where(data%10 == 6)
print(data[datac])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 6 16 26 36 46 56 66 76 86 96]


## Exercise numpy and csv

1. load the csv file: befkbhalderstatkode.csv into a numpy ndarray
2. How many german children of 0 years were there in Copenhagen in 2015?
3. create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
4. create a new function like previous so that it can sum values for all ages if age is not provided to the function
5. further add functionality to sum values if citizenship or area was not provided to function.
6. create a new function that can also give average values for each year if year whas not provided.
7. create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015
8. Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively
9. Find out what age most French people have in 2015

In [70]:
#task 1
with open("../../data/befkbhalderstatkode.csv") as f:
    kkdata = f.readlines()
    for line in kkdata[:20]:
        print(line.strip().split(','))
    bef_stats_df = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
    dd = bef_stats_df
    
    

['AAR', 'BYDEL', 'ALDER', 'STATKODE', 'PERSONER']
['2015', '1', '0', '5100', '614']
['2015', '1', '0', '5104', '2']
['2015', '1', '0', '5106', '1']
['2015', '1', '0', '5110', '1']
['2015', '1', '0', '5120', '4']
['2015', '1', '0', '5126', '1']
['2015', '1', '0', '5130', '5']
['2015', '1', '0', '5140', '3']
['2015', '1', '0', '5150', '5']
['2015', '1', '0', '5154', '1']
['2015', '1', '0', '5164', '3']
['2015', '1', '0', '5170', '3']
['2015', '1', '0', '5180', '3']
['2015', '1', '0', '5228', '1']
['2015', '1', '0', '5306', '2']
['2015', '1', '0', '5390', '1']
['2015', '1', '0', '5448', '1']
['2015', '1', '0', '5464', '1']
['2015', '1', '0', '5472', '1']


In [74]:
    #task 2
    bef_stats_df = np.genfromtxt(kkdata, delimiter=',', dtype=np.uint, skip_header=1)
    dd = bef_stats_df
    
    mask = (dd[:,0] == 2015) & (dd[:,2] == 0) & (dd[:,3] == 5180)
    print(dd[mask])
    print('sum all the cph areas\n',np.sum(dd[mask][:,4]))

[[2015    1    0 5180    3]
 [2015    2    0 5180    5]
 [2015    3    0 5180    7]
 [2015    4    0 5180    1]
 [2015    5    0 5180    1]
 [2015    6    0 5180    2]
 [2015    8    0 5180    2]
 [2015    9    0 5180    6]
 [2015   10    0 5180    8]]
sum all the cph areas
 35


In [83]:
#task 3
def population_data(aar, bydel, alder, statkode):
    mask = (dd[:, 0] == aar) & (dd[:,1] == bydel) & (dd[:,2] == alder) & (dd[:,3] == statkode)
    return dd[mask]


print(population_data(2015, 1, 18, 5100))


[[2015    1   18 5100  378]]
